# Generated by Django 6.0.7 on 2026-09-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0003_remove_courseslist_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseslist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
