# Generated by Django 6.0.7 on 2026-09-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps1', '0004_remove_courseslist_description_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('profile', 'course'), name='unique_profile_course'),
        ),
    ]
